---
- name: Build Images
  hosts: azure
  gather_facts: true
  tasks:
  - name: make the shell script executable
    shell:
      "sudo chmod +x buildImages.sh"

  - name: Build images and push to docker hub
    shell:
      "./buildImages.sh"
    register: build_image_output

  - name: check build image output
    debug:
      msg: "{{  build_image_output }}"